version: 2.1
orbs:
  node: circleci/node@2.1.1
  browser-tools: circleci/browser-tools@1.0.0

jobs:
  
  test:
    executor:
      name: node/default
      tag: lts
    steps:
      - checkout
      - node/install-packages
      - browser-tools/install-browser-tools
      - run:
          name: Test
          command: npm test

workflows:
  version: 2

  test:
    jobs:
      - test
